parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Jakala\Validator\JsonSchemaValidator:

    jakala.json.schema.validator:
        alias: Jakala\Validator\JsonSchemaValidator
